-- Which are the top-selling product categories?
SELECT 
	p.product_category_name AS product_category,
	count(*) AS total_sales
FROM 
	olist_order_items_dataset oi
	JOIN olist_products_dataset p ON oi.product_id = p.product_id
GROUP BY product_category
ORDER BY total_sales DESC

-- What is the average order value for each product category?
SELECT
	p.product_category_name AS product_category,
	AVG(oi.price) AS average_price
FROM
	olist_order_items_dataset oi
	JOIN olist_products_dataset p ON oi.product_id = p.product_id
GROUP BY product_category
ORDER BY average_price DESC

-- How many orders were placed in each state?
SELECT 
	c.customer_state as customer_state,
	count(*) as orders
FROM
	olist_orders_dataset o
	JOIN olist_customers_dataset c ON o.customer_id = c.customer_id
GROUP BY customer_state
ORDER BY orders DESC

-- What is the distribution of customer states across different product categories?
SELECT
	customers.customer_state as customer_state,
	products.product_category_name as product_category,
	count(*) as orders
FROM
	olist_orders_dataset orders
	JOIN olist_customers_dataset customers ON orders.customer_id = customers.customer_id
	JOIN olist_order_items_dataset order_items ON order_items.order_id = orders.order_id
	JOIN olist_products_dataset products ON order_items.product_id = products.product_id
GROUP BY
	customer_state, product_category
ORDER BY
	customer_state, product_category
	
-- Which sellers have the highest number of orders?
SELECT
	s.seller_id AS seller_id,
	s.seller_city AS seller_city,
	s.seller_state AS seller_state,
	count(*) AS total_orders 
FROM
	olist_order_items_dataset o
	JOIN olist_sellers_dataset s ON s.seller_id = o.seller_id
GROUP BY
	s.seller_id
ORDER BY
	total_orders DESC

-- What is the average time it takes for an order to be delivered?
SELECT
        AVG((strftime('%s', order_delivered_customer_date) 
		-  strftime('%s', order_purchase_timestamp))/86400) AS average_days
FROM
    olist_orders_dataset

-- Which sellers have received reviews with the highest scores?
SELECT 
	o.seller_id,
	AVG(r.review_score) AS average_score,
	COUNT(*) AS total_reviews
FROM
	olist_order_reviews_dataset r
	INNER JOIN olist_order_items_dataset o ON r.order_id = o.order_id
GROUP BY
	o.seller_id
HAVING
	total_reviews > 10
ORDER BY
	average_score DESC

-- What is the total sales revenue generated by each product category?
SELECT 
	p.product_category_name as product_category,
	SUM(o.price) as revenue
FROM
	olist_products_dataset p
	LEFT JOIN olist_order_items_dataset O ON p.product_id = o.product_id
GROUP BY
	product_category
ORDER BY
	revenue DESC

	


	